// examples/react/src/chat-widget.tsx
import * as React from 'react';
import type { RefCallback } from 'react';
import type { ToasterPosition } from 'cincin-react';

type Clearance = {
  x: number;
  y: number;
};

type ChatWidgetProps = {
  position: ToasterPosition;
  onClearance: (clearance: Clearance) => void;
};

const GAP = 12;

function ChatWidget({ position, onClearance }: ChatWidgetProps) {
  const [open, setOpen] = React.useState(false);
  const [y, x] = position.split('-');

  const ref = React.useCallback<RefCallback<HTMLElement>>(
    (element) => {
      if (element === null) {
        return;
      }

      const observer = new ResizeObserver(() => {
        onClearance({
          x: element.offsetWidth + GAP,
          y: element.offsetHeight + GAP,
        });
      });

      observer.observe(element);

      return () => {
        observer.disconnect();
        onClearance({ x: 0, y: 0 });
      };
    },
    [onClearance]
  );

  return (
    <div ref={ref} data-widget data-y={y} data-x={x} data-open={open}>
      <button type="button" aria-expanded={open} onClick={() => setOpen(!open)}>
        {open ? 'Chat ↓' : '💬'}
      </button>

      {open && <p>Hi! Nobody is reading this, it is here to take up room.</p>}
    </div>
  );
}

export { ChatWidget };
export type { Clearance };

// examples/vue/src/ChatWidget.vue
<script lang="ts">
type Clearance = {
  x: number;
  y: number;
};

export type { Clearance };
</script>

<script setup lang="ts">
import { ref, watchEffect } from 'vue';
import type { ToasterPosition } from 'cincin-vue';

const props = defineProps<{
  position: ToasterPosition;
}>();

const emit = defineEmits<{
  clearance: [clearance: Clearance];
}>();

const GAP = 12;

const open = ref(false);
const element = ref<HTMLElement | null>(null);

watchEffect((onCleanup) => {
  const node = element.value;

  if (node === null) {
    return;
  }

  const observer = new ResizeObserver(() => {
    emit('clearance', {
      x: node.offsetWidth + GAP,
      y: node.offsetHeight + GAP,
    });
  });

  observer.observe(node);

  onCleanup(() => {
    observer.disconnect();
    emit('clearance', { x: 0, y: 0 });
  });
});
</script>

<template>
  <div
    ref="element"
    data-widget
    :data-y="props.position.split('-')[0]"
    :data-x="props.position.split('-')[1]"
    :data-open="open"
  >
    <button type="button" :aria-expanded="open" @click="open = !open">
      {{ open ? 'Chat ↓' : '💬' }}
    </button>

    <p v-if="open">Hi! Nobody is reading this, it is here to take up room.</p>
  </div>
</template>
