// packages/cincin-solid/src/core/use-toasts.ts
import type { Toast, Presenter } from 'cincin/presenter';
import type { Accessor } from 'solid-js';
import { createSnapshotAccessor } from '../shared/snapshot-accessor';

function useToasts<Content extends {}>(
  presenter: Presenter<Content>
): Accessor<ReadonlyArray<Toast<Content>>> {
  return createSnapshotAccessor(presenter);
}

export { useToasts };

// packages/cincin-react/src/core/use-toasts.ts
import type { Toast, Presenter } from 'cincin/presenter';
import { useSyncExternalStore } from 'react';
import { getServerSnapshot } from '../shared/ssr';

function useToasts<Content extends {}>(
  presenter: Presenter<Content>
): ReadonlyArray<Toast<Content>> {
  return useSyncExternalStore(
    presenter.subscribe,
    presenter.getSnapshot,
    getServerSnapshot
  );
}

export { useToasts };
