// packages/cincin-solid/src/core/use-focus-loop.ts
import { createFocusLoopController, createFocusLoopHandlers } from 'cincin/dom';
import type { FocusLoopController, StackLayout } from 'cincin/dom';
import { onCleanup, onMount } from 'solid-js';
import type { MaybeAccessor } from '../shared/maybe-accessor';

type FocusLoopOptions = {
  layout: StackLayout;
};

type FocusLoopHandlers = {
  onFocusIn: (event: FocusEvent) => void;
  onFocusOut: (event: FocusEvent) => void;
  onKeyDown: (event: KeyboardEvent) => void;
  onPointerDown: () => void;
  onPointerUp: () => void;
  onPointerCancel: () => void;
};

type FocusLoop = {
  /** The machine itself: `jump` is the consumer's to bind, to a hotkey or anything else. */
  loop: FocusLoopController;
  /** For the region: the loop's edge is the landmark, not the list. */
  handlers: FocusLoopHandlers;
};

function useFocusLoop(options: MaybeAccessor<FocusLoopOptions>): FocusLoop {
  // A setup-time read on purpose: the layout is read once.
  const { layout } = typeof options === 'function' ? options() : options;
  const loop = createFocusLoopController(layout);
  const { element } = createFocusLoopHandlers(loop);

  onMount(function mountLoop() {
    loop.mount();
    onCleanup(() => loop.unmount());
  });

  return {
    loop,
    handlers: {
      onFocusIn: element.focusin,
      onFocusOut: element.focusout,
      onKeyDown: element.keydown,
      onPointerDown: element.pointerdown,
      onPointerUp: element.pointerup,
      onPointerCancel: element.pointercancel,
    },
  };
}

export { useFocusLoop };
export type { FocusLoopOptions, FocusLoopHandlers, FocusLoop };

// packages/cincin-react/src/core/use-focus-loop.ts
import { createFocusLoopController, createFocusLoopHandlers } from 'cincin/dom';
import type { FocusLoopController, StackLayout } from 'cincin/dom';
import * as React from 'react';
import type { FocusEvent, KeyboardEvent } from 'react';

type FocusLoopOptions = {
  layout: StackLayout;
};

type FocusLoopHandlers<T extends HTMLElement> = {
  onFocus: (event: FocusEvent<T>) => void;
  onBlur: (event: FocusEvent<T>) => void;
  onKeyDown: (event: KeyboardEvent<T>) => void;
  onPointerDown: () => void;
  onPointerUp: () => void;
  onPointerCancel: () => void;
};

type FocusLoop<T extends HTMLElement> = {
  /** The machine itself: `jump` is the consumer's to bind, to a hotkey or anything else. */
  loop: FocusLoopController;
  /** For the region: the loop's edge is the landmark, not the list. */
  handlers: FocusLoopHandlers<T>;
};

function useFocusLoop<T extends HTMLElement>(
  options: FocusLoopOptions
): FocusLoop<T> {
  const [{ loop, handlers }] = React.useState(() => {
    const controller = createFocusLoopController(options.layout);
    const { element } = createFocusLoopHandlers<
      FocusEvent<T>,
      FocusEvent<T>,
      KeyboardEvent<T>
    >(controller);

    return {
      loop: controller,
      handlers: {
        onFocus: element.focusin,
        onBlur: element.focusout,
        onKeyDown: element.keydown,
        onPointerDown: element.pointerdown,
        onPointerUp: element.pointerup,
        onPointerCancel: element.pointercancel,
      },
    };
  });

  React.useEffect(
    function mountLoop() {
      loop.mount();

      return () => loop.unmount();
    },
    [loop]
  );

  return { loop, handlers };
}

export { useFocusLoop };
export type { FocusLoopOptions, FocusLoopHandlers, FocusLoop };
