// packages/cincin-solid/src/core/use-stack.ts
import { createStackLayout } from 'cincin/dom';
import type { StackLayout, StackLayoutOptions } from 'cincin/dom';
import type { Toast } from 'cincin/presenter';
import { createEffect, onCleanup } from 'solid-js';
import { access } from '../shared/maybe-accessor';
import type { MaybeAccessor } from '../shared/maybe-accessor';

type StackOptions = StackLayoutOptions;

/**
 * A thin binding over the `cincin/dom` stack layout: the primitive
 * owns the instance and feeds it entries from an effect — after the
 * render phase, so every card's ref has registered its element by
 * then (the pass skips unregistered keys), and still before paint.
 * Cards read their slots through `useSlot(element, { layout, key })`.
 */
function useStack(
  entries: MaybeAccessor<ReadonlyArray<Pick<Toast, 'key' | 'phase'>>>,
  options?: MaybeAccessor<StackOptions | undefined>
): { layout: StackLayout } {
  // The body locator rides only the creation: it is read once by the
  // layout, and setOptions leaves it alone.
  const initial = access(options) ?? {};
  const layout = createStackLayout({
    order: initial.order ?? 'stack',
    visible: initial.visible ?? 3,
    gap: initial.gap ?? 12,
    ...(initial.body && { body: initial.body }),
  });

  createEffect(function syncOptions() {
    const live = access(options) ?? {};

    layout.setOptions({
      order: live.order ?? 'stack',
      visible: live.visible ?? 3,
      gap: live.gap ?? 12,
    });
  });

  createEffect(function syncEntries() {
    layout.setEntries(
      (access(entries) ?? []).map((toast) => ({
        key: toast.key,
        leaving: toast.phase === 'leaving',
      }))
    );
  });

  onCleanup(() => {
    layout.destroy();
  });

  return { layout };
}

export { useStack };
export type { StackOptions };

// packages/cincin-react/src/toaster/use-stack.ts
import { useLayoutEffect, useRef, useState } from 'react';
import { createStackLayout } from 'cincin/dom';
import type { StackLayoutConfig } from 'cincin/dom';
import type { Toast, ToastKey } from 'cincin/presenter';
import { useRefMap } from '../shared/use-ref-map';

type StackOptions = StackLayoutConfig;

/** A thin binding over the `cincin/dom` stack layout: the controller
 * owns the geometry (slots, heights, the ResizeObserver); the hook
 * feeds it commits and hands out stable card refs. */
function useStack(
  entries: ReadonlyArray<Pick<Toast, 'key' | 'phase'>>,
  options: StackOptions = {}
) {
  const { order = 'stack', visible = 3, gap = 12 } = options;
  const [layout] = useState(() => createStackLayout({ order, visible, gap }));
  const cards = useRefMap<ToastKey, HTMLElement>({
    onChange: (key, element) => layout.setCard(key, element),
  });
  const aliveIds = useRef(new Set<ToastKey>());

  useLayoutEffect(
    function syncConfig() {
      layout.setConfig({ order, visible, gap });
    },
    [layout, order, visible, gap]
  );

  useLayoutEffect(
    function syncEntries() {
      layout.setEntries(
        entries.map((toast) => ({
          key: toast.key,
          leaving: toast.phase === 'leaving',
        }))
      );

      // The data pass is the only reliable "truly gone" signal: the
      // registry entries of departed toasts are released here, never
      // from ref cleanups (those re-run while the toast is alive).
      const alive = new Set(entries.map((toast) => toast.key));
      for (const key of aliveIds.current) {
        if (!alive.has(key)) {
          cards.release(key);
        }
      }
      aliveIds.current = alive;
    },
    [layout, cards, entries]
  );

  useLayoutEffect(
    function destroyOnUnmount() {
      return () => {
        layout.destroy();
      };
    },
    [layout]
  );

  return { cardRef: cards.getRef };
}

export { useStack };
