// packages/cincin-react/src/core/context.tsx
'use client';

import type { Toaster, ToastEntry } from 'cincin';
import { createContext, useContext } from 'react';
import type { ReactNode } from 'react';
import { useToastEntries as useToastEntriesOf } from './use-toast-entries';

function createToasterContext<Content extends {} = string>(
  defaultToaster?: Toaster<Content>
) {
  const Context = createContext<Toaster<Content> | null>(
    defaultToaster ?? null
  );

  function ToasterProvider(props: {
    toaster: Toaster<Content>;
    children: ReactNode;
  }) {
    return (
      <Context.Provider value={props.toaster}>
        {props.children}
      </Context.Provider>
    );
  }

  function useToaster(toaster?: Toaster<Content>): Toaster<Content> {
    const fromContext = useContext(Context);
    const resolved = toaster ?? fromContext ?? null; // Normalize both nullish values: a JS consumer can mount the provider with an undefined toaster.

    if (resolved === null) {
      throw new Error(
        '[cincin] no toaster available. Pass one to createToasterContext, wrap the tree in <ToasterProvider>, or provide an instance explicitly.'
      );
    }

    return resolved;
  }

  function useToastEntries(
    toaster?: Toaster<Content>
  ): ReadonlyArray<ToastEntry<Content>> {
    const instance = useToaster(toaster);

    return useToastEntriesOf(instance);
  }

  return { ToasterProvider, useToaster, useToastEntries };
}

export { createToasterContext };

// packages/cincin-angular/src/core/context.ts
import type { Toaster, ToastEntry } from 'cincin';
import { InjectionToken, inject } from '@angular/core';
import type { Provider, Signal } from '@angular/core';
import { injectToastEntries as injectToastEntriesOf } from './inject-toast-entries';

function createToasterContext<Content extends {} = string>(
  defaultToaster?: Toaster<Content>
) {
  // A root factory carries the default: an injector without a provider
  // resolves to it, and a `provideToaster` anywhere down the tree wins.
  const TOASTER = new InjectionToken<Toaster<Content> | null>(
    'cincin:toaster',
    { providedIn: 'root', factory: () => defaultToaster ?? null }
  );

  function provideToaster(toaster: Toaster<Content>): Provider {
    return { provide: TOASTER, useValue: toaster };
  }

  function injectToaster(toaster?: Toaster<Content>): Toaster<Content> {
    const resolved = toaster ?? inject(TOASTER) ?? null; // Normalize both nullish values: a JS consumer can provide an undefined toaster.

    if (resolved === null) {
      throw new Error(
        '[cincin] no toaster available. Pass one to createToasterContext, add provideToaster() to an ancestor, or provide an instance explicitly.'
      );
    }

    return resolved;
  }

  function injectToastEntries(
    toaster?: Toaster<Content>
  ): Signal<ReadonlyArray<ToastEntry<Content>>> {
    return injectToastEntriesOf(injectToaster(toaster));
  }

  return { provideToaster, injectToaster, injectToastEntries };
}

export { createToasterContext };
