// packages/cincin-react/src/core/use-viewport.ts
import type { Presenter } from 'cincin/presenter';
import { createViewportController, createViewportHandlers } from 'cincin/dom';
import type { ViewportOptions } from 'cincin/dom';
import * as React from 'react';
import type { FocusEvent, SyntheticEvent } from 'react';

type ViewportHandlers<T extends HTMLElement> = {
  onMouseEnter: (event: SyntheticEvent<T>) => void;
  onMouseMove: (event: SyntheticEvent<T>) => void;
  onMouseLeave: (event: SyntheticEvent<T>) => void;
  onLostPointerCapture: (event: SyntheticEvent<T>) => void;
  onPointerDown: (event: SyntheticEvent<T>) => void;
  onPointerUp: (event: SyntheticEvent<T>) => void;
  onPointerCancel: (event: SyntheticEvent<T>) => void;
  onFocus: (event: SyntheticEvent<T>) => void;
  onBlur: (event: FocusEvent<T>) => void;
};

type Viewport<T extends HTMLElement> = {
  expanded: boolean;
  handlers: ViewportHandlers<T>;
};

function useViewport<T extends HTMLElement, Content extends {}>(
  presenter: Presenter<Content>,
  options: ViewportOptions = {}
): Viewport<T> {
  const { collapseDelay } = options;

  const [{ controller, viewport }] = React.useState(() => {
    const c = createViewportController({ collapseDelay });
    const v = createViewportHandlers<SyntheticEvent<T>, FocusEvent<T>>(c);

    return {
      controller: c,
      viewport: v,
    };
  });

  React.useEffect(
    function syncOptions() {
      controller.setOptions({ collapseDelay });
    },
    [controller, collapseDelay]
  );

  React.useEffect(
    function destroyController() {
      return () => controller.destroy();
    },
    [controller]
  );

  const expanded = React.useSyncExternalStore(
    controller.subscribe,
    controller.getSnapshot,
    getServerSnapshot
  );

  React.useEffect(
    function listenOutside() {
      document.addEventListener('pointerdown', viewport.document.pointerdown);

      return () =>
        document.removeEventListener(
          'pointerdown',
          viewport.document.pointerdown
        );
    },
    [viewport.document.pointerdown]
  );

  React.useEffect(
    function endHoverWhenEmpty() {
      return presenter.subscribe(() => {
        if (presenter.count() === 0) {
          controller.hover(false);
        }
      });
    },
    [presenter, controller]
  );

  React.useEffect(
    function holdWhileOpen() {
      if (!expanded) {
        return;
      }

      presenter.pause();
      const unsubscribe = presenter.subscribe((event) => {
        if (event.type === 'entered') {
          presenter.pause(event.toast.key);
        }
      });

      return () => {
        unsubscribe();
        presenter.resume();
      };
    },
    [presenter, expanded]
  );

  return {
    expanded,
    handlers: {
      onMouseEnter: viewport.element.mouseenter,
      onMouseMove: viewport.element.mousemove,
      onMouseLeave: viewport.element.mouseleave,
      onLostPointerCapture: viewport.element.lostpointercapture,
      onPointerDown: viewport.element.pointerdown,
      onPointerUp: viewport.element.pointerup,
      onPointerCancel: viewport.element.pointercancel,
      onFocus: viewport.element.focusin,
      onBlur: viewport.element.focusout,
    },
  };
}

export { useViewport };
export type { ViewportHandlers, Viewport };

// utils

const getServerSnapshot = () => false;

// packages/cincin-solid/src/core/use-viewport.ts
import { createViewportController, createViewportHandlers } from 'cincin/dom';
import type { ViewportOptions } from 'cincin/dom';
import type { Presenter } from 'cincin/presenter';
import { createEffect, on, onCleanup, onMount } from 'solid-js';
import type { Accessor } from 'solid-js';
import { access } from '../shared/maybe-accessor';
import type { MaybeAccessor } from '../shared/maybe-accessor';
import { createSnapshotAccessor } from '../shared/snapshot-accessor';

type ViewportHandlers = {
  onMouseEnter: (event: MouseEvent) => void;
  onMouseMove: (event: MouseEvent) => void;
  onMouseLeave: (event: MouseEvent) => void;
  onLostPointerCapture: (event: PointerEvent) => void;
  onPointerDown: (event: PointerEvent) => void;
  onPointerUp: (event: PointerEvent) => void;
  onPointerCancel: (event: PointerEvent) => void;
  onFocusIn: (event: FocusEvent) => void;
  onFocusOut: (event: FocusEvent) => void;
};

type Viewport = {
  expanded: Accessor<boolean>;
  handlers: ViewportHandlers;
};

function useViewport<Content extends {}>(
  presenter: Presenter<Content>,
  options?: MaybeAccessor<ViewportOptions | undefined>
): Viewport {
  const controller = createViewportController(access(options));
  const viewport = createViewportHandlers(controller);

  onCleanup(() => controller.destroy());

  createEffect(function syncOptions() {
    controller.setOptions(access(options) ?? {});
  });

  const expanded = createSnapshotAccessor(controller);

  onMount(function listenOutside() {
    document.addEventListener('pointerdown', viewport.document.pointerdown);

    onCleanup(() =>
      document.removeEventListener('pointerdown', viewport.document.pointerdown)
    );
  });

  onMount(function endHoverWhenEmpty() {
    onCleanup(
      presenter.subscribe(() => {
        if (presenter.count() === 0) {
          controller.hover(false);
        }
      })
    );
  });

  createEffect(
    on(expanded, function holdWhileOpen(open) {
      if (!open) {
        return;
      }

      presenter.pause();
      const unsubscribe = presenter.subscribe((event) => {
        if (event.type === 'entered') {
          presenter.pause(event.toast.key);
        }
      });

      onCleanup(() => {
        unsubscribe();
        presenter.resume();
      });
    })
  );

  return {
    expanded,
    handlers: {
      onMouseEnter: viewport.element.mouseenter,
      onMouseMove: viewport.element.mousemove,
      onMouseLeave: viewport.element.mouseleave,
      onLostPointerCapture: viewport.element.lostpointercapture,
      onPointerDown: viewport.element.pointerdown,
      onPointerUp: viewport.element.pointerup,
      onPointerCancel: viewport.element.pointercancel,
      onFocusIn: viewport.element.focusin,
      onFocusOut: viewport.element.focusout,
    },
  };
}

export { useViewport };
export type { ViewportHandlers, Viewport };
