// packages/cincin-react/src/core/use-toast-entries.ts
import type { ToastEntry, Toaster } from 'cincin';
import { useSyncExternalStore } from 'react';
import { getServerSnapshot } from '../shared/ssr';

function useToastEntries<Content extends {}>(
  toaster: Toaster<Content>
): ReadonlyArray<ToastEntry<Content>> {
  return useSyncExternalStore(
    toaster.subscribe,
    toaster.getSnapshot,
    getServerSnapshot
  );
}

export { useToastEntries };

// packages/cincin-solid/src/core/use-toast-entries.ts
import type { ToastEntry, Toaster } from 'cincin';
import type { Accessor } from 'solid-js';
import { createSnapshotAccessor } from '../shared/snapshot-accessor';

function useToastEntries<Content extends {}>(
  toaster: Toaster<Content>
): Accessor<ReadonlyArray<ToastEntry<Content>>> {
  return createSnapshotAccessor(toaster);
}

export { useToastEntries };
