// packages/cincin-react/src/core/use-slot.ts
import { createSlotObserver } from 'cincin/dom';
import type { StackLayout, StackSlot } from 'cincin/dom';
import type { ToastKey } from 'cincin/presenter';
import { useCallback, useState, useSyncExternalStore } from 'react';
import type { RefCallback } from 'react';

type SlotOptions = {
  layout: StackLayout;
  key: ToastKey;
};

/**
 * One card's slot, live: a slot observer under the hood, bound through
 * `useSyncExternalStore` (layout passes run before paint, and external
 * store updates flush synchronously, so a measured height lands in the
 * same frame). The ref registers the card's element for measurement;
 * React 19 runs its cleanup on unmount. The layout is read once, like
 * the toaster in `usePresenter` (remount to switch); the `key` stays
 * live through `setOptions`, re-stated on every render before the
 * store read.
 */
function useSlot(options: SlotOptions): {
  ref: RefCallback<HTMLElement>;
  slot: StackSlot | undefined;
} {
  const { layout, key } = options;

  const [observer] = useState(() => createSlotObserver(layout, { key }));
  observer.setOptions({ key });

  const slot = useSyncExternalStore(
    observer.subscribe,
    observer.getSnapshot,
    observer.getSnapshot
  );

  const ref: RefCallback<HTMLElement> = useCallback(
    // A key change re-runs the callback: the old call's cleanup
    // releases the old key's registration, this one claims the new.
    (element) => (element === null ? undefined : observer.observe(element)),
    [observer, key]
  );

  return { ref, slot };
}

export { useSlot };
export type { SlotOptions };

// packages/cincin-solid/src/core/use-slot.ts
import { createSlotObserver } from 'cincin/dom';
import type { StackLayout, StackSlot } from 'cincin/dom';
import type { ToastKey } from 'cincin/presenter';
import { createRenderEffect, onCleanup } from 'solid-js';
import type { Accessor } from 'solid-js';
import { access } from '../shared/maybe-accessor';
import type { MaybeAccessor } from '../shared/maybe-accessor';
import { createSnapshotAccessor } from '../shared/snapshot-accessor';

type SlotOptions = {
  layout: StackLayout;
  key: ToastKey;
};

/**
 * One card's slot, live: a slot observer under the hood, bound to a
 * signal (layout passes run synchronously, so a measured height lands
 * in the same frame). The element source registers the card's element
 * for measurement. The layout and the key are read once: a card lives
 * and dies with its list key, so they cannot change under a live
 * instance.
 *
 * Registration rides a render effect on purpose: a signal ref lands
 * during the card's render, so the element is registered before the
 * region's `setEntries` effect runs its pass (the pass skips
 * unregistered keys) — the Solid spelling of refs-before-effects.
 */
function useSlot(
  element: MaybeAccessor<HTMLElement | undefined>,
  options: SlotOptions
): Accessor<StackSlot | undefined> {
  const { layout, key } = options;
  const observer = createSlotObserver(layout, { key });
  const slot = createSnapshotAccessor(observer);

  createRenderEffect(() => {
    const el = access(element);

    if (el === undefined) {
      return;
    }

    onCleanup(observer.observe(el));
  });

  return slot;
}

export { useSlot };
export type { SlotOptions };
