// packages/cincin-react/src/core/use-stack.ts
import * as React from 'react';
import { createStackLayout } from 'cincin/dom';
import type { StackLayoutOptions } from 'cincin/dom';
import type { Toast } from 'cincin/presenter';

type StackOptions = StackLayoutOptions;

function useStack(
  entries: ReadonlyArray<Pick<Toast, 'key' | 'phase'>>,
  options: StackOptions = {}
) {
  const { order, visible, gap } = options;

  const [layout] = React.useState(() => createStackLayout(options));

  React.useLayoutEffect(
    function syncOptions() {
      layout.setOptions({ order, visible, gap });
    },
    [layout, order, visible, gap]
  );

  React.useLayoutEffect(
    function syncEntries() {
      layout.setEntries(
        entries.map((toast) => ({
          key: toast.key,
          leaving: toast.phase === 'leaving',
        }))
      );
    },
    [layout, entries]
  );

  React.useLayoutEffect(
    function destroyOnUnmount() {
      return () => {
        layout.destroy();
      };
    },
    [layout]
  );

  return { layout };
}

export { useStack };
export type { StackOptions };

// packages/cincin-solid/src/core/use-stack.ts
import { createStackLayout } from 'cincin/dom';
import type { StackLayout, StackLayoutOptions } from 'cincin/dom';
import type { Toast } from 'cincin/presenter';
import { createEffect, onCleanup } from 'solid-js';
import { access } from '../shared/maybe-accessor';
import type { MaybeAccessor } from '../shared/maybe-accessor';

type StackOptions = StackLayoutOptions;

function useStack(
  entries: MaybeAccessor<ReadonlyArray<Pick<Toast, 'key' | 'phase'>>>,
  options?: MaybeAccessor<StackOptions | undefined>
): { layout: StackLayout } {
  const layout = createStackLayout(access(options));

  createEffect(function syncOptions() {
    layout.setOptions(access(options) ?? {});
  });

  createEffect(function syncEntries() {
    layout.setEntries(
      (access(entries) ?? []).map((toast) => ({
        key: toast.key,
        leaving: toast.phase === 'leaving',
      }))
    );
  });

  onCleanup(() => {
    layout.destroy();
  });

  return { layout };
}

export { useStack };
export type { StackOptions };
