// packages/cincin-react/src/core/use-presenter.ts
import type { Toaster } from 'cincin';
import { createPresenter } from 'cincin/presenter';
import type { Presenter, PresenterOptions } from 'cincin/presenter';
import * as React from 'react';

/**
 * A presenter over the given toaster, alive as long as the component:
 * mounted on commit, unmounted on cleanup (StrictMode's double effect
 * is countered by the presenter's mount counting). The toaster is read
 * once, like a query client: remount to switch. Options stay live and
 * land before paint (the layout effect, like the stack's): a raised
 * max promotes in the same frame.
 */
function usePresenter<ToastContent extends {} = string>(
  toaster: Toaster<ToastContent>,
  options?: PresenterOptions
): Presenter<ToastContent> {
  const { max, exitDuration } = options ?? {};

  const resolvedOptions = React.useMemo<PresenterOptions>(
    () => ({ max, exitDuration }),
    [max, exitDuration]
  );

  const [presenter] = React.useState(() =>
    createPresenter(toaster, resolvedOptions)
  );

  React.useEffect(() => {
    presenter.mount();

    return () => presenter.unmount();
  }, [presenter]);

  React.useLayoutEffect(() => {
    presenter.setOptions(resolvedOptions);
  }, [presenter, resolvedOptions]);

  return presenter;
}

export { usePresenter };

// packages/cincin-solid/src/core/use-presenter.ts
import type { Toaster } from 'cincin';
import { createPresenter } from 'cincin/presenter';
import type { Presenter, PresenterOptions } from 'cincin/presenter';
import { createRenderEffect, onCleanup, onMount } from 'solid-js';
import { access } from '../shared/maybe-accessor';
import type { MaybeAccessor } from '../shared/maybe-accessor';

/**
 * A presenter over the given toaster, alive as long as the component:
 * mounted on mount, unmounted on cleanup (the pair rides inside
 * onMount, so a server render that never mounts never unmounts
 * either). The toaster is read once, like a query client: remount to
 * switch. Options stay live through a getter and land in the render
 * phase, before paint: a raised max promotes in the same frame.
 */
function usePresenter<ToastContent extends {} = string>(
  toaster: Toaster<ToastContent>,
  options?: MaybeAccessor<PresenterOptions>
): Presenter<ToastContent> {
  const presenter = createPresenter(toaster, access(options) ?? {});

  onMount(() => {
    presenter.mount();
    onCleanup(presenter.unmount);
  });

  createRenderEffect(() => {
    presenter.setOptions(access(options) ?? {});
  });

  return presenter;
}

export { usePresenter };
